name: wedding_invitation
description: Nhat and Oanh wedding invitation

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_swiper: ^1.1.6
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/landscape.jpg
    - assets/img/portrait.jpg
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/google_fonts/DancingScript-Bold.ttf
        - asset: assets/google_fonts/DancingScript-Medium.ttf
        - asset: assets/google_fonts/DancingScript-Regular.ttf
        - asset: assets/google_fonts/DancingScript-SemiBold.ttf
    - family: Yanone
      fonts:
        - asset: assets/google_fonts/YanoneKaffeesatz-Bold.ttf
        - asset: assets/google_fonts/YanoneKaffeesatz-ExtraLight.ttf
        - asset: assets/google_fonts/YanoneKaffeesatz-Light.ttf
        - asset: assets/google_fonts/YanoneKaffeesatz-Medium.ttf
        - asset: assets/google_fonts/YanoneKaffeesatz-Regular.ttf
        - asset: assets/google_fonts/YanoneKaffeesatz-SemiBold.ttf
